global using Microsoft.Toolkit.Mvvm.ComponentModel;
global using Microsoft.Toolkit.Mvvm.Input;
global using AuthTemplate.ViewModels;
global using AuthTemplate.Views;
global using System.Collections.ObjectModel;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.Runtime.CompilerServices;
global using System.Text.Json;
